name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run typecheck
        working-directory: apps/web

      - name: Setup Supabse CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start local Supabase
        run: supabase start

      - name: Export Supabase credentials
        run: supabase status --output env | sed 's/"//g' >> $GITHUB_ENV

      - name: Run tests
        run: npm run test
        working-directory: apps/web
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ env.API_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ env.SERVICE_ROLE_KEY }}